'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const STORE='keithogram.challenge.v2';
const state=Object.assign({players:[],active:'',scores:[],quiz:0,theme:'dark',font:17,tea:false},JSON.parse(localStorage.getItem(STORE)||'{}'));
const sayings=["Tea recommended. Dictionary optional.","Proceed carefully. Keith has probably already solved it.","If Keith can't solve it, it's probably wrong.","No Googling. Keith will know.","Put the kettle on before attempting clue 7.","Keith has temporarily left for a bacon sandwich at PJ's.","Results are being verified at PJ's.","Keith remains unconvinced by everybody else's scores.","Alderney reports fair puzzling conditions.","The Admiralty requests legible answers.","Brown sauce is not a solving aid.","Model boats may be consulted, discreetly.","The harbour master has sharpened a pencil.","Clue setters deny everything.","Bacon privileges must be earned.","A calm sea never made a cryptic champion.","Keith's dictionary remains suspiciously warm.","The fleet awaits your final answer.","Tea first. Hubris later.","All appeals will be heard at PJ's."];
function save(){localStorage.setItem(STORE,JSON.stringify(state))}
function normal(s){return String(s||'').toUpperCase().replace(/[^A-Z0-9]/g,'')}
function toast(msg){$('#toast').textContent=msg;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',3500)}
function applyDisplay(){document.body.classList.toggle('dark',state.theme==='dark');document.body.classList.toggle('tea',state.tea);document.documentElement.style.setProperty('--size',state.font+'px');$('#themeBtn').textContent=state.theme==='dark'?'☀ Light mode':'☾ Dark mode';$('#teaBtn').setAttribute('aria-pressed',state.tea)}
function playerOptions(){const s=$('#existingPlayer');s.innerHTML='<option value="">Select a name</option>'+state.players.map(n=>`<option ${n===state.active?'selected':''}>${escapeHtml(n)}</option>`).join('');$('#activePlayer').textContent=state.active?`Playing as ${state.active}.`:'No player selected.'}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function clueHtml(c,i,prefix){return `<div class="clue"><label for="${prefix}${i}"><span class="number">${i+1}.</span><span>${escapeHtml(c.clue)}</span></label><input class="answer" id="${prefix}${i}" data-answer="${escapeHtml(c.answer)}" autocomplete="off" spellcheck="false"><div class="feedback" hidden></div></div>`}
function renderQuiz(){const q=KEITHOGRAMS[state.quiz];$('#quizTitle').textContent=q.title;$('#difficulty').textContent=q.difficulty;$('#progress').textContent=`Keithogram ${state.quiz+1} of ${KEITHOGRAMS.length}`;$('#mainClues').innerHTML=q.clues.map((c,i)=>clueHtml(c,i,'q')).join('');$('#bonusClues').innerHTML=q.bonus.map((c,i)=>clueHtml(c,i,'b')).join('');$('#result').hidden=true;$('#keithism').textContent=sayings[Math.floor(Math.random()*sayings.length)];save();window.scrollTo({top:0,behavior:'smooth'})}
function mark(revealOnly=false){const q=KEITHOGRAMS[state.quiz], all=[...q.clues,...q.bonus], inputs=$$('.answer');let main=0,sea=0;inputs.forEach((inp,i)=>{const ok=normal(inp.value)===normal(all[i].answer);if(ok){if(i<q.clues.length)main++;else sea++}const f=inp.nextElementSibling;f.hidden=false;f.className='feedback '+(ok?'correct':'incorrect');f.innerHTML=`${ok?'Correct.':'Answer: <strong>'+escapeHtml(all[i].answer)+'</strong>.'} <span class="explanation">${escapeHtml(all[i].explanation)}</span>`});if(revealOnly)return;const total=main+sea,max=all.length,pct=Math.round(total/max*100);const award=total===max?"PJ's Platinum Bacon Sandwich":total>=10?"PJ's Grand Bacon Sandwich":total>=6?"Standard PJ's Bacon Sandwich":"Toast. Bacon remains pending.";const verdict=total===max?"Suspiciously good. A review panel has been convened.":total>=9?"Good effort. Extra brown sauce authorised.":"More study required before progressing to bacon.";$('#result').hidden=false;$('#result').innerHTML=`<h3>Keith's Verdict</h3><p><strong>${total}/${max} (${pct}%)</strong>, including ${sea}/${q.bonus.length} maritime.</p><p>${verdict}</p><p class="award">${award}</p>`;if(state.active){state.scores.push({name:state.active,quiz:q.id,title:q.title,score:total,total:max,pct,maritime:sea,maritimeTotal:q.bonus.length,date:new Date().toISOString()});save();renderBoards();sendShared(state.scores.at(-1))}else toast('Select a player to save this result.')}
async function sendShared(score){if(!CONFIG.webAppUrl)return;try{await fetch(CONFIG.webAppUrl,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain'},body:JSON.stringify({Name:score.name,QuizId:score.quiz,QuizTitle:score.title,Score:score.score,Total:score.total,Percentage:score.pct,Maritime:score.maritime,MaritimeTotal:score.maritimeTotal})})}catch(e){toast('Shared scoreboard unavailable; score saved in this browser.') }}
function aggregates(){const m={};state.scores.forEach(s=>{m[s.name]??={name:s.name,scores:[],sea:0,seaTotal:0};m[s.name].scores.push(s);m[s.name].sea+=s.maritime;m[s.name].seaTotal+=s.maritimeTotal});return Object.values(m)}
function renderBoards(){const a=aggregates().map(p=>({...p,completed:p.scores.length,avg:Math.round(p.scores.reduce((x,s)=>x+s.pct,0)/p.scores.length),best:Math.max(...p.scores.map(s=>s.pct)),perfect:p.scores.filter(s=>s.pct===100).length,seaPct:p.seaTotal?Math.round(p.sea/p.seaTotal*100):0}));a.sort((x,y)=>y.avg-x.avg||y.best-x.best);$('#league tbody').innerHTML=a.length?a.map((p,i)=>`<tr><td>${i+1}</td><td>${escapeHtml(p.name)}</td><td>${p.completed}</td><td>${p.avg}%</td><td>${p.best}%</td><td>${p.perfect}</td></tr>`).join(''):'<tr><td colspan="6">No completed Keithograms yet.</td></tr>';const sea=[...a].sort((x,y)=>y.seaPct-x.seaPct);const titles=['First Sea Lord','Fleet Captain','Chief Navigator','Able Seaman','Cabin Boy'];$('#admiralty tbody').innerHTML=sea.length?sea.map((p,i)=>`<tr><td>${i+1}</td><td>${escapeHtml(p.name)}</td><td>${p.sea}/${p.seaTotal} (${p.seaPct}%)</td><td>${titles[Math.min(i,4)]}</td></tr>`).join(''):'<tr><td colspan="4">The board awaits its first result.</td></tr>';$('#activity tbody').innerHTML=state.scores.length?[...state.scores].reverse().slice(0,10).map(s=>`<tr><td>${escapeHtml(s.name)}</td><td>${escapeHtml(s.title)}</td><td>${s.score}/${s.total}</td><td>${new Date(s.date).toLocaleDateString('en-GB')}</td></tr>`).join(''):'<tr><td colspan="4">No recent activity.</td></tr>';const leader=a[0]?.name;$('#championship').textContent=!leader?'The Admiralty awaits the opening result.':leader.toLowerCase()===String(CONFIG.keithChampionName).toLowerCase()?"Keith remains at the top. The Admiralty is calm.":"Keith has requested an inquiry into the scoring process."}
$('#quizForm').addEventListener('submit',e=>{e.preventDefault();mark(false)});$('#revealBtn').onclick=()=>mark(true);$('#resetBtn').onclick=()=>{$$('.answer').forEach(i=>i.value='');$$('.feedback').forEach(f=>f.hidden=true);$('#result').hidden=true};$('#nextBtn').onclick=()=>{state.quiz=(state.quiz+1)%KEITHOGRAMS.length;renderQuiz()};$('#prevBtn').onclick=()=>{state.quiz=(state.quiz-1+KEITHOGRAMS.length)%KEITHOGRAMS.length;renderQuiz()};$('#randomBtn').onclick=()=>{state.quiz=Math.floor(Math.random()*KEITHOGRAMS.length);renderQuiz()};$('#themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';applyDisplay();save()};$('#fontUp').onclick=()=>{state.font=Math.min(24,state.font+1);applyDisplay();save()};$('#fontDown').onclick=()=>{state.font=Math.max(14,state.font-1);applyDisplay();save()};$('#teaBtn').onclick=()=>{state.tea=!state.tea;applyDisplay();save();toast(state.tea?'Tea-Time Mode activated. A comfortable puzzle experience has been prepared.':'Tea-Time Mode deactivated.')};$('#existingPlayer').onchange=e=>{state.active=e.target.value;playerOptions();save()};$('#usePlayer').onclick=()=>{const n=$('#newPlayer').value.trim();if(!n)return toast('Please enter a player name.');if(!state.players.includes(n))state.players.push(n);state.active=n;$('#newPlayer').value='';playerOptions();save()};applyDisplay();playerOptions();renderQuiz();renderBoards();
